# NumPy와 Pandas 실습

---

## 학습 개요

1. **학습 주제**
  - **NumPy**: `ndarray` 의 벡터 연산, 통계 함수, 조건 필터, 정렬, 2차원 배열과 브로드캐스팅
  - **Pandas 조회**: `DataFrame` 의 구조 확인(`head`/`info`/`describe`), 파일 입출력
  - **Pandas 필터**: 조건 필터(`&`,`|`), `isin`,`str.contains`, `nlargest`, `loc`,`iloc`
  - **Pandas 집계**: `groupby`, `agg`, 다중 `groupby`, `pivot_table`

2. **학습 목표**
  - NumPy 배열로 반복문 없이 **벡터 연산**과 **통계**를 수행할 수 있다.
  - `reshape` 와 `axis` 로 2차원 배열의 **축별 집계**를 할 수 있다.
  - DataFrame 을 조회,필터링하고 원하는 행만 **추출**할 수 있다.
  - `groupby` 와 `pivot_table` 로 **그룹별 집계**를 만들 수 있다.

3. **핵심 개념**
  - **NumPy 배열 (ndarray)**: 같은 타입의 숫자 묶음. 배열 전체에 산술 연산을 적용하는 **벡터화** 덕분에 빠릅니다.
  - **브로드캐스팅**: 모양이 다른 배열끼리 연산할 때 작은 쪽이 자동으로 확장됩니다.
  - **Pandas DataFrame / Series**: 행,열로 된 표(엑셀 시트와 같은 모양). 컬럼마다 자료형이 다를 수 있습니다.
  - **groupby**: 같은 값끼리 묶어 합,평균을 내는 작업으로, 엑셀 피벗 테이블과 같습니다.

4. **선행 지식**
  - 라이브 1 «Python 기초와 API,LLM 연결» 의 `list`, `dict`, 반복문, 함수
  - Python 설치 및 Jupyter Notebook 또는 Google Colab 사용 방법을 숙지하고 있어야 합니다.

## 실습 구성

1. **학습 방향**
  - **실습 구성 방식**: 각 단계의 TODO 영역(`None`)을 채웁니다. 빈칸을 올바르게 채우면 `assert` 가 통과하고 `TODO N 통과!` 가 출력됩니다. 정답을 확인하는 `assert` 코드는 수정하지 말고 진행해 주세요.
  - **Required Package**
    ```
    python>=3.12,<3.13
    numpy>=2.5.0,<3
    pandas>=3.0.0,<4
    ```

2. **Step 요약**
  - **Step 1**: NumPy 배열 생성과 벡터 연산
  - **Step 2**: NumPy 통계, 조건 필터, 정렬
  - **Step 3**: 2차원 배열 - `reshape`, 축별 집계, 브로드캐스팅
  - **Step 4**: Pandas DataFrame 만들고 조회하기
  - **Step 5**: 조건 필터링
  - **Step 6**: 상위,하위 행 추출과 `loc` 인덱싱
  - **Step 7**: `groupby` 집계와 `pivot_table`
  - **Step 8**: 미니 프로젝트 - 카페 매출 리포트

3. **문제 설명**
  - **데이터셋**: 외부 파일 없이 코드로 생성하는 카페 음료 판매 더미 데이터(메뉴 3종, 200행, `seed=42` 로 고정). 지역,메뉴,단가,수량,매출 컬럼을 가집니다.
  - **문제 개요**: NumPy와 Pandas로 데이터를 조회하고 필터링한 뒤 집계하는 과정을 익힙니다.
  - **요구사항 요약**
    - **NumPy**: 배열 생성, 벡터 연산, 통계 함수, boolean indexing, 정렬, `reshape`, 축별 집계, 브로드캐스팅
    - **Pandas 조회**: `head`/`tail`/`info`/`describe`/`shape`/`dtypes`/`value_counts`, `read_csv`/`to_csv`
    - **Pandas 필터**: `df[조건]`, `&`/`|`, `isin`, `str.contains`, `nlargest`/`nsmallest`, `loc`/`iloc`
    - **Pandas 집계**: `groupby`, `agg`, 다중 `groupby`, `pivot_table`, `reset_index`

4. **학습 문제: Step-TODO**
  - **Step 1**: TODO 1(배열 생성,벡터 연산)
  - **Step 2**: TODO 2(통계,필터,정렬)
  - **Step 3**: TODO 3(`reshape`,축별 집계), TODO 4(브로드캐스팅)
  - **Step 4**: TODO 5(조회 메서드)
  - **Step 5**: TODO 6(조건 필터링)
  - **Step 6**: TODO 7(상위,하위 행과 `loc`)
  - **Step 7**: TODO 8(`groupby`,`agg` 집계), TODO 9(다중 `groupby`,`pivot_table`)
  - **Step 8**: TODO 10(카페 매출 리포트)

## Install & Import

이미 라이브러리가 설치된 환경이라면 `!pip install` 줄은 건너뛰어도 됩니다. Colab 처럼 새 환경이라면 한 번 실행해 주세요.

In [8]:
# !pip install -q "numpy>=2.5.0,<3" "pandas>=3.0.0,<4"
import numpy as np
import pandas as pd

print("numpy:", np.__version__, "| pandas:", pd.__version__)

numpy: 2.5.1 | pandas: 3.0.5

## Step 1: NumPy 배열과 벡터 연산

### Concept Check: 리스트와 NumPy 배열의 차이

파이썬 리스트는 `가격 * 2` 를 계산하면 리스트를 두 번 이어붙입니다. 원소별로 계산하려면 반복문이 필요합니다.

**NumPy 배열(`ndarray`)** 은 같은 자료형의 숫자를 묶어 두고, 산술 연산을 **배열 전체에** 적용합니다. 이걸 **벡터화(vectorization)** 라고 합니다.

```python
가격 = np.array([4000, 4500, 5000])
가격 * 0.9     # array([3600., 4050., 4500.]), 각 가격에 10% 할인 적용
```

리스트는 각 원소를 반복해서 계산합니다. NumPy 배열은 같은 자료형의 데이터가 메모리에 연속으로 저장되며, 내부 연산은 C로 구현되어 있습니다.

| 데이터 크기 | 파이썬(s) | NumPy(s) | 차이 |
| --- | --- | --- | --- |
| 1,000 | 0.0000154 | 0.0000053 | 2.9배 |
| 100,000 | 0.0013191 | 0.0000637 | 20.7배 |
| 1,000,000 | 0.0109592 | 0.0003693 | 29.7배 |

`mean`,`sum`,`max` 같은 통계 함수도 내장돼 있고, `ndarray` 는 `dtype`(int64,float64)과 `shape`(모양) 정보까지 가집니다.

**배열 만들기**: `np.array(리스트)`, `np.arange(n)`(0~n-1), `np.zeros(n)`, `np.ones(n)`, `np.linspace(a, b, n)`(a~b 를 n등분)

In [9]:
# 리스트와 배열의 차이
파이썬_리스트 = [1, 2, 3]
print(파이썬_리스트 * 2)            # [1, 2, 3, 1, 2, 3]  , 이어붙이기

넘파이_배열 = np.array([1, 2, 3])
print(넘파이_배열 * 2)              # [2 4 6]  , 원소별 2배
print(넘파이_배열.dtype, 넘파이_배열.shape)  # int64 (3,)

# 배열 만들기
print(np.arange(5))          # [0 1 2 3 4]
print(np.zeros(3))           # [0. 0. 0.]
print(np.ones(3))            # [1. 1. 1.]
print(np.linspace(0, 1, 5))  # [0. 0.25 0.5 0.75 1.]

[1, 2, 3, 1, 2, 3]
[2 4 6]
int64 (3,)
[0 1 2 3 4]
[0. 0. 0.]
[1. 1. 1.]
[0.   0.25 0.5  0.75 1.  ]

In [10]:
# 같은 합계를 구해도 계산 방식이 다르다 (값은 동일)
arr = np.arange(1_000_000)
arr_sum = arr.sum()                 # 벡터 연산: 내부 C 루프로 합산
list_sum = sum(range(1_000_000))    # 파이썬 반복문: 원소마다 순회
print(arr_sum, list_sum)            # 499999500000 499999500000

499999500000 499999500000

### TODO 1: 배열 생성과 벡터 연산

**요구사항**
- 단가, 수량 배열로 할인가와 매출을 반복문 없이 계산합니다.

**제한조건**
- 정답 확인용 `assert` 줄은 수정하지 않습니다. `None` 자리만 채웁니다.
- 반복문(`for`) 없이 배열 연산만 사용합니다.

**힌트**
- `배열 * 숫자` 는 모든 원소에, `배열 * 배열` 은 같은 위치끼리 적용됩니다.
- 0부터 n-1 배열은 `np.arange(n)`, 0으로 채운 배열은 `np.zeros(n)`, 구간 n등분은 `np.linspace(a, b, n)`.

In [11]:
단가 = np.array([4000, 4500, 5000, 5500, 6000])
수량 = np.array([2, 1, 3, 5, 1])

# 1. 단가의 90%(10% 할인가)를 할인가 에 할당해 주세요.
할인가 = 단가 * 0.9
assert np.allclose(할인가, [3600, 4050, 4500, 4950, 5400]), "할인가 계산이 올바르지 않습니다."

# 2. 단가 × 수량(같은 위치끼리 곱)을 매출 에 할당해 주세요.
매출 = 단가 * 수량
assert list(매출) == [8000, 4500, 15000, 27500, 6000], "매출 계산이 올바르지 않습니다."

# 3. 0부터 4까지 배열을 arange5 에 할당해 주세요.
arange5 = np.arange(5)
assert list(arange5) == [0, 1, 2, 3, 4], "arange 결과가 올바르지 않습니다."

# 4. 0으로 채운 길이 3 배열을 zeros3 에 할당해 주세요.
zeros3 = np.zeros(3)
assert list(zeros3) == [0.0, 0.0, 0.0], "zeros 결과가 올바르지 않습니다."

# 5. 0~1 구간을 5등분한 배열을 구간5 에 할당해 주세요.
구간5 = np.linspace(0, 1, 5)
assert np.allclose(구간5, [0.0, 0.25, 0.5, 0.75, 1.0]), "linspace 결과가 올바르지 않습니다."

print("TODO 1 통과!")

TODO 1 통과!

## Step 2: 통계, 조건 필터, 정렬

### Concept Check: 통계 함수와 boolean indexing

- **통계 함수**: `.sum()` 합 / `.mean()` 평균 / `.max()` 최대 / `.min()` 최소 / `.std()` 표준편차(퍼진 정도)
  - 배열 메서드(`매출.mean()`)로도, 함수(`np.mean(매출)`)로도 호출할 수 있습니다.
- **조건 필터(boolean indexing)**: `배열[배열 >= 10000]` - 조건이 `True` 인 원소만 추출. 여러 조건은 `&`(그리고),`|`(또는)로 묶고 **각 조건을 괄호로 감쌉니다.**
- **정렬**: `np.sort(배열)`(오름차순, 원본 유지), `np.sort(배열)[::-1]`(내림차순), `np.argsort(배열)`(정렬 순서의 **인덱스**만 반환)

In [12]:
매출 = np.array([8000, 4500, 15000, 25000, 6000])

print(매출.sum())     # 58500   총매출
print(매출.mean())    # 11700.0 평균
print(매출.max())     # 25000   최고
print(매출.std())     # 표준편차

# 조건 필터: 범위 지정은 각 조건을 괄호로 감싸고 & 로 결합
print(매출[매출 >= 10000])                    # [15000 25000]
print(매출[(매출 >= 5000) & (매출 <= 15000)])  # [ 8000 15000  6000]

# 정렬
print(np.sort(매출))        # [ 4500  6000  8000 15000 25000]
print(np.sort(매출)[::-1])  # [25000 15000  8000  6000  4500]  내림차순
print(np.argsort(매출))     # [1 4 0 2 3], 작은 값부터의 인덱스

58500
11700.0
25000
7560.42326857432
[15000 25000]
[ 8000 15000  6000]
[ 4500  6000  8000 15000 25000]
[25000 15000  8000  6000  4500]
[1 4 0 2 3]

### TODO 2: 통계, 필터, 정렬

**요구사항**
- 매출 배열에서 통계값을 구하고, 조건 필터와 정렬을 적용합니다.

**제한조건**
- 정답 확인용 `assert` 줄은 수정하지 않습니다. `None` 자리만 채웁니다.

**힌트**
- 통계: `매출.sum()`, `매출.mean()`, `매출.max()`, `매출.std()`.
- 조건 필터: `매출[매출 >= 10000]`. 정렬: `np.sort(매출)`, 내림차순은 `np.sort(매출)[::-1]`.
- 정렬 순서의 인덱스는 `np.argsort(매출)`.

In [14]:
매출 = np.array([8000, 4500, 15000, 25000, 6000])

# 1. 합계를 총매출 에 할당해 주세요.
총매출 = 매출.sum()
assert 총매출 == 58500, "합계가 올바르지 않습니다."

# 2. 평균을 평균매출 에 할당해 주세요.
평균매출 = 매출.mean()
assert np.isclose(평균매출, 11700.0), "평균이 올바르지 않습니다."

# 3. 최댓값을 최고매출 에 할당해 주세요.
최고매출 = 매출.max()
assert 최고매출 == 25000, "최댓값이 올바르지 않습니다."

# 4. 표준편차를 표준편차 에 할당해 주세요.
표준편차 = 매출.std()
assert np.isclose(표준편차, np.std([8000, 4500, 15000, 25000, 6000])), "표준편차가 올바르지 않습니다."

# 5. 1만 이상인 값만 골라 고매출 에 할당해 주세요.
고매출 = 매출[매출 >= 10000]
assert list(고매출) == [15000, 25000], "조건 필터가 올바르지 않습니다."

# 6. 5천 이상 1만5천 이하인 값만 골라 중간매출 에 할당해 주세요. (괄호 필수)
중간매출 = 매출[(매출 >= 5000) & (매출 <= 15000)]
assert list(중간매출) == [8000, 15000, 6000], "범위 필터가 올바르지 않습니다."

# 7. 오름차순 정렬을 오름차순 에 할당해 주세요.
오름차순 = np.sort(매출)
assert list(오름차순) == [4500, 6000, 8000, 15000, 25000], "오름차순 정렬이 올바르지 않습니다."

# 8. 내림차순 정렬을 내림차순 에 할당해 주세요.
내림차순 = np.sort(매출)[::-1]
assert list(내림차순) == [25000, 15000, 8000, 6000, 4500], "내림차순 정렬이 올바르지 않습니다."

# 9. 정렬 순서의 인덱스를 정렬인덱스 에 할당해 주세요.
정렬인덱스 = np.argsort(매출)
assert list(정렬인덱스) == [1, 4, 0, 2, 3], "argsort 결과가 올바르지 않습니다."

print("TODO 2 통과!")

TODO 2 통과!

## Step 3: 2차원 배열 - `reshape`, 축별 집계, 브로드캐스팅

### Concept Check: 모양을 바꾸고 축으로 집계하기

- **2차원 배열**: `np.array([[1,2,3], [4,5,6]])` 로 만들거나 `arr.reshape(행, 열)` 로 모양을 바꿉니다. 원소 수가 같아야 합니다.
- **`-1`**: 한쪽 차원을 `-1` 로 두면 나머지가 자동 계산됩니다. `arr.reshape(3, -1)`의 결과는 `(3, 2)`입니다.
- **인덱싱**: `매출표[0, 1]` 은 0행 1열. `.T` 는 행과 열을 뒤집습니다(전치).
- **축별 집계**: `axis=0` 은 **열 방향**(세로로 합), `axis=1` 은 **행 방향**(가로로 합)입니다.

```python
표 = np.arange(6).reshape(2, 3)   # [[0 1 2]
                                  #  [3 4 5]]
표.sum(axis=0)   # [3 5 7], 열별 합
표.sum(axis=1)   # [3 12], 행별 합
```

**브로드캐스팅**: 모양이 다른 배열끼리 연산할 때 작은 쪽이 자동으로 늘어나 맞춰집니다.

- `1D 배열 + 스칼라`: 모든 원소에 적용
- `1D + 1D`(크기 같음): 같은 위치의 원소끼리 연산
- `1D + 2D`: 행 또는 열에 맞게 확장하여 연산

`np.newaxis` 로 축을 하나 늘리면 `(3,)` 배열을 `(3, 1)` 로 만들어 2차원 배열과 맞출 수 있습니다.

In [15]:
매출표 = np.array([
    [8000, 4500, 15000],   # 서울
    [6000, 5200, 10000],   # 부산
])

print(매출표.shape)    # (2, 3): 2행 3열
print(매출표[0, 1])    # 4500, 0행 1열
print(매출표.T)        # 행과열 뒤집기 (3행 2열)

arr = np.arange(6)              # [0 1 2 3 4 5]
표 = arr.reshape(2, 3)
print(표)
print(arr.reshape(3, -1))       # 3행으로 변환, 열 수는 2로 계산
print(표.sum(axis=0))           # [3 5 7]  , 열별 합
print(표.sum(axis=1))           # [3 12]   , 행별 합

# 브로드캐스팅 결과: (3, 2)
단가 = np.array([4000, 5000, 6000])         # (3,)
수량표 = np.array([[1, 2], [3, 1], [5, 2]])  # (3, 2)
결과 = 단가[:, np.newaxis] * 수량표
print(결과)
# [[ 4000  8000]
#  [15000  5000]
#  [30000 12000]]

(2, 3)
4500
[[ 8000  6000]
 [ 4500  5200]
 [15000 10000]]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]
[3 5 7]
[ 3 12]
[[ 4000  8000]
 [15000  5000]
 [30000 12000]]

### TODO 3: `reshape` 와 축별 집계

**요구사항**
- 1차원 배열을 2차원으로 바꾸고 축별 합을 구한 뒤 전치합니다.

**제한조건**
- 정답 확인용 `assert` 줄은 수정하지 않습니다. `None` 자리만 채웁니다.

**힌트**
- `axis=0` 은 열 방향(세로로 합), `axis=1` 은 행 방향(가로로 합)입니다.
- 한쪽 차원을 자동 계산하려면 `-1` 을 넣습니다. 전치는 `표.T`.

In [16]:
arr = np.arange(6)          # [0 1 2 3 4 5]

# 1. arr 을 2행 3열로 바꿔 표 에 할당해 주세요.
표 = arr.reshape(2, 3)
assert 표.shape == (2, 3), "reshape 모양이 올바르지 않습니다."

# 2. arr 을 3행으로 바꾸되 열은 자동 계산되게 해 표3 에 할당해 주세요.
표3 = arr.reshape(3, -1)
assert 표3.shape == (3, 2), "-1 자동 계산이 올바르지 않습니다."

# 3. 열별 합(axis=0)을 열합 에 할당해 주세요.
열합 = 표.sum(axis=0)
assert list(열합) == [3, 5, 7], "열별 합이 올바르지 않습니다."

# 4. 행별 합(axis=1)을 행합 에 할당해 주세요.
행합 = 표.sum(axis=1)
assert list(행합) == [3, 12], "행별 합이 올바르지 않습니다."

# 5. 행과 열을 뒤집은 전치를 전치 에 할당해 주세요.
전치 = 표.T
assert 전치.shape == (3, 2), "전치 모양이 올바르지 않습니다."

print("TODO 3 통과!")

TODO 3 통과!

### TODO 4: 브로드캐스팅

**요구사항**
- 메뉴별 단가 `(3,)` 와 지역별 판매 수량표 `(3, 2)` 를 곱해 메뉴×지역 매출표를 만듭니다.

**제한조건**
- 정답 확인용 `assert` 줄은 수정하지 않습니다. `None` 자리만 채웁니다.
- 반복문 없이 브로드캐스팅만 사용합니다.

**힌트**
- `(3,)` 를 `(3, 1)` 로 늘리려면 `단가[:, np.newaxis]` 를 씁니다.
- `(3, 1) * (3, 2)` 는 열 방향으로 자동 확장되어 `(3, 2)` 가 됩니다.

In [17]:
단가 = np.array([4000, 5000, 6000])           # (3,) 메뉴 3종
수량표 = np.array([[1, 2], [3, 1], [5, 2]])   # (3, 2) 메뉴 × 지역 2곳

# 1. 단가에 축을 하나 늘려 (3, 1) 모양으로 만들어 단가열 에 할당해 주세요.
단가열 = 단가[:, np.newaxis]
assert 단가열.shape == (3, 1), "np.newaxis 로 모양을 바꾸지 못했습니다."

# 2. 단가열 과 수량표 를 곱해 매출표 에 할당해 주세요.
매출표 = 단가열 * 수량표
assert 매출표.shape == (3, 2), "브로드캐스팅 결과 모양이 올바르지 않습니다."
assert 매출표.tolist() == [[4000, 8000], [15000, 5000], [30000, 12000]], "매출표 값이 올바르지 않습니다."

# 3. 지역별 총매출(열 방향 합)을 지역합 에 할당해 주세요.
지역합 = 매출표.sum(axis=0)
assert list(지역합) == [49000, 25000], "지역별 합이 올바르지 않습니다."

print("TODO 4 통과!")

TODO 4 통과!

## Step 4: Pandas DataFrame 만들고 조회하기

### Concept Check: 표를 다루는 도구, DataFrame

**DataFrame** 은 행과 열로 된 2차원 표입니다(엑셀 시트와 같은 모양). 한 열은 **Series**(1차원)이고, 컬럼마다 자료형이 다를 수 있습니다(지역은 문자열, 단가는 정수). 이 점이 단일 타입만 담는 NumPy 배열과 다릅니다.

| 엑셀 | Pandas |
| --- | --- |
| 시트 | DataFrame |
| 행/열 | DataFrame 의 행/열 |
| VLOOKUP | `merge` |
| 피벗 테이블 | `groupby` |

- **인덱스(index)**: 행을 식별하는 라벨(기본값은 `0, 1, 2 ...` 정수)
- **컬럼(columns)**: 열 이름의 묶음
- 내부 값은 NumPy 2차원 배열로 저장됩니다(`df.values`).

**조회 메서드**

| 메서드 | 반환 | 용도 |
| --- | --- | --- |
| `df.head(n)` | DataFrame | 위 n행 미리보기 (기본 5행) |
| `df.tail(n)` | DataFrame | 아래 n행 미리보기 |
| `df.info()` | 출력만 | 컬럼,자료형,결측 요약 |
| `df.describe()` | DataFrame | 숫자 컬럼 통계(count,mean,std,min,max) |
| `df.shape` | (행, 열) 튜플 | 크기 확인 |
| `df.dtypes` | Series | 각 컬럼 자료형 |
| `df['컬럼'].value_counts()` | Series | 값별 빈도 |

**파일 입출력**: `pd.read_csv('경로')` 로 파일을 표로 읽고, `df.to_csv('경로', index=False)` 로 저장합니다. 한글이 깨지면 `encoding='utf-8-sig'` 또는 `'cp949'` 를 지정합니다.

| 컬럼 | 의미 | 예시 |
| --- | --- | --- |
| 지역 | 판매 지역 | 서울 / 부산 / 대전 / 광주 |
| 메뉴 | 음료 이름 | 아메리카노 / 카페라떼 / 바닐라라떼 |
| 단가 | 한 잔 가격 | 4000 ~ 6000 |
| 수량 | 주문 수량 | 1 ~ 5 |
| 매출 | 단가 × 수량 | 자동 계산 (파생 컬럼) |

In [18]:
# 카페 음료 판매 더미 데이터 (외부 파일 없이 생성, seed 고정)
np.random.seed(42)
n = 200
지역 = np.random.choice(["서울", "부산", "대전", "광주"], n)
메뉴 = np.random.choice(["아메리카노", "카페라떼", "바닐라라떼"], n)
단가 = np.random.choice([4000, 4500, 5000, 5500, 6000], n)
수량 = np.random.randint(1, 6, n)   # 1 이상 6 미만 , 1~5

df = pd.DataFrame({"지역": 지역, "메뉴": 메뉴, "단가": 단가, "수량": 수량})
df["매출"] = df["단가"] * df["수량"]   # 파생 컬럼

print(df.shape)     # (200, 5)
print(df.index)     # RangeIndex(start=0, stop=200, step=1)
print(df.columns)   # Index(['지역', '메뉴', '단가', '수량', '매출'], ...)
print(type(df["단가"]))   # <class 'pandas.core.series.Series'>
df.head()

(200, 5)
RangeIndex(start=0, stop=200, step=1)
Index(['지역', '메뉴', '단가', '수량', '매출'], dtype='str')
<class 'pandas.Series'>

   지역     메뉴    단가  수량     매출
0  대전  바닐라라떼  4000   5  20000
1  광주  바닐라라떼  6000   3  18000
2  서울  아메리카노  5000   3  15000
3  대전  아메리카노  5500   1   5500
4  대전   카페라떼  4000   4  16000

In [19]:
# 파일로 저장했다가 다시 읽어 오기 (한글은 utf-8-sig 로 저장하면 엑셀에서도 안 깨짐)
df.to_csv("cafe_sales.csv", index=False, encoding="utf-8-sig")

불러온df = pd.read_csv("cafe_sales.csv", encoding="utf-8-sig")
print(불러온df.shape)   # (200, 5)
불러온df.head()

(200, 5)

   지역     메뉴    단가  수량     매출
0  대전  바닐라라떼  4000   5  20000
1  광주  바닐라라떼  6000   3  18000
2  서울  아메리카노  5000   3  15000
3  대전  아메리카노  5500   1   5500
4  대전   카페라떼  4000   4  16000

### TODO 5: 조회 메서드

**요구사항**
- 조회 메서드로 데이터의 크기, 통계, 분포를 확인합니다.

**제한조건**
- 정답 확인용 `assert` 줄은 수정하지 않습니다. `None` 자리만 채웁니다.

**힌트**
- 위 5행 `df.head(5)`, 아래 3행 `df.tail(3)`, 크기 `df.shape` (튜플이라 `행수, 열수 = df.shape` 로 풉니다).
- 숫자 통계 `df.describe()`, 컬럼 자료형 `df.dtypes`, 값별 빈도 `df["지역"].value_counts()`.

In [20]:
# 1. 위에서 5행을 앞5행 에 할당해 주세요.
앞5행 = df.head(5)
assert len(앞5행) == 5, "head(5) 결과가 올바르지 않습니다."

# 2. 아래에서 3행을 뒤3행 에 할당해 주세요.
뒤3행 = df.tail(3)
assert len(뒤3행) == 3, "tail(3) 결과가 올바르지 않습니다."

# 3. (행, 열) 크기를 행수, 열수 에 풀어 담아 주세요.
행수, 열수 = df.shape
assert 행수 == 200 and 열수 == 5, "shape 가 올바르지 않습니다."

# 4. 숫자 컬럼 통계를 통계 에 할당해 주세요.
통계 = df.describe()
assert "매출" in 통계.columns, "describe 결과가 올바르지 않습니다."

# 5. 각 컬럼의 자료형을 자료형 에 할당해 주세요.
자료형 = df.dtypes
assert len(자료형) == 5, "dtypes 결과가 올바르지 않습니다."

# 6. 지역별 행 수(빈도)를 지역분포 에 할당해 주세요.
지역분포 = df["지역"].value_counts()
assert 지역분포.sum() == 200 and len(지역분포) == 4, "value_counts 결과가 올바르지 않습니다."

print("TODO 5 통과!")
df.info()

TODO 5 통과!
<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지역      200 non-null    str
 1   메뉴      200 non-null    str
 2   단가      200 non-null    int64
 3   수량      200 non-null    int32
 4   매출      200 non-null    int64
dtypes: int32(1), int64(2), str(2)
memory usage: 7.2 KB

## Step 5: 조건 필터링

### Concept Check: 조건으로 행 골라내기

- `df['컬럼']` - 한 열을 선택합니다(Series).
- `df[조건]` - 조건이 `True` 인 행만 남깁니다.
- 조건 결합: `&`(그리고),`|`(또는). **각 조건은 반드시 괄호로 감쌉니다.**
- `df['메뉴'].isin([...])` - 리스트에 포함된 값만
- `df['메뉴'].str.contains('라떼')` - 특정 글자를 포함한 행만
- `df['메뉴'].str.startswith('카페')` - 특정 글자로 시작하는 행만

**자주 하는 실수**

- 조건 결합에는 `&`/`|` 를 씁니다. 파이썬의 `and`/`or` 는 쓸 수 없습니다(Pandas 규칙).
- 괄호를 빼면 연산자 우선순위 때문에 의도와 다른 결과가 나오거나 `TypeError` 가 납니다.
- `==` 는 비교, `=` 는 대입입니다. 필터에는 `==` 를 씁니다.
- 한글 컬럼명도 `df['지역']` 으로 접근할 수 있습니다.

```python
# 괄호 누락 , 에러
df[df["매출"] >= 10000 & df["메뉴"] == "아메리카노"]
# 올바른 작성
df[(df["매출"] >= 10000) & (df["메뉴"] == "아메리카노")]
```

### TODO 6: 조건으로 행 골라내기

**요구사항**
- 단일, 복합 조건과 문자열 검색으로 원하는 행만 추출합니다.

**제한조건**
- 정답 확인용 `assert` 줄은 수정하지 않습니다. `None` 자리만 채웁니다.
- 복합 조건은 `&`/`|` 를 쓰고 각 조건을 괄호로 감쌉니다. (`and`/`or` 금지)

**힌트**
- 단일 `df[df["지역"] == "서울"]`, 복합 `df[(조건1) & (조건2)]`.
- 글자 포함 `df["메뉴"].str.contains("라떼")`, 시작 `str.startswith("카페")`, 목록 포함 `df["메뉴"].isin([...])`.

In [21]:
# 1. 지역이 "서울" 인 행만 서울df 에 할당해 주세요.
서울df = df[df["지역"] == "서울"]
assert (서울df["지역"] == "서울").all(), "서울 필터가 올바르지 않습니다."

# 2. 매출 1만 이상이면서 메뉴가 "아메리카노" 인 행을 고매출아메 에 할당해 주세요. (괄호 필수)
고매출아메 = df[(df["매출"] >= 10000) & (df["메뉴"] == "아메리카노")]
assert (고매출아메["매출"] >= 10000).all() and (고매출아메["메뉴"] == "아메리카노").all(), "복합 조건 필터가 올바르지 않습니다."

# 3. 메뉴에 "라떼" 가 들어간 행을 라떼df 에 할당해 주세요.
라떼df = df[df["메뉴"].str.contains("라떼")]
assert 라떼df["메뉴"].str.contains("라떼").all(), "문자열 포함 필터가 올바르지 않습니다."

# 4. 메뉴가 "카페" 로 시작하는 행을 카페시작 에 할당해 주세요.
카페시작 = df[df["메뉴"].str.startswith("카페")]
assert set(카페시작["메뉴"].unique()) == {"카페라떼"}, "startswith 필터가 올바르지 않습니다."

# 5. 메뉴가 "아메리카노" 또는 "카페라떼" 인 행을 선택메뉴 에 할당해 주세요.
선택메뉴 = df[df["메뉴"].isin(["아메리카노", "카페라떼"])]
assert set(선택메뉴["메뉴"].unique()) <= {"아메리카노", "카페라떼"}, "isin 필터가 올바르지 않습니다."

print("TODO 6 통과!")

TODO 6 통과!

## Step 6: 상위,하위 행 추출과 `loc` 인덱싱

### Concept Check: 원하는 행,열을 정확히 집어내기

**상위,하위 행 추출**

| 메서드 | 동작 |
| --- | --- |
| `df.nlargest(n, '컬럼')` | 해당 컬럼 기준 상위 n행 |
| `df.nsmallest(n, '컬럼')` | 해당 컬럼 기준 하위 n행 |
| `df.sample(n, random_state=42)` | 무작위 n행 (seed 고정 가능) |
| `df.sort_values('컬럼', ascending=False)` | 컬럼 기준 정렬 |

**`loc` 와 `iloc`**

- `df.loc[행 조건, 열 이름]` - 행과 열을 **동시에** 지정합니다. `df[조건]` 은 행만 고르지만 `loc` 은 열까지 함께 고릅니다.
- 조건에 맞는 값을 바꿀 때도 씁니다: `df.loc[df['단가'] < 4000, '단가'] = 4000` (조건부 대입).
- `df.iloc[0, 1]` - **위치(정수)** 로 선택합니다.

```python
df.loc[df["지역"] == "서울", "매출"]   # 서울 지역의 매출 컬럼만
df.iloc[0, 1]                        # 0행 1열 (위치 기반)
```

In [22]:
# 상위,하위 행과 무작위 표본
print(df.nlargest(3, "매출")[["지역", "메뉴", "매출"]])
print(df.nsmallest(3, "수량")[["지역", "메뉴", "수량"]])
print(df.sample(3, random_state=42)[["지역", "메뉴", "매출"]])

# loc: 행 조건 + 열 이름
print(df.loc[df["지역"] == "서울", "매출"].head())
# iloc: 위치 기반
print(df.iloc[0, 1])   # 0행 1열 (메뉴)

    지역     메뉴     매출
6   서울  바닐라라떼  30000
31  서울   카페라떼  30000
55  광주   카페라떼  30000
    지역     메뉴  수량
3   대전  아메리카노   1
7   서울  바닐라라떼   1
10  대전  바닐라라떼   1
    지역     메뉴     매출
95  부산  아메리카노  25000
15  서울  바닐라라떼  22500
30  서울  바닐라라떼   8000
2     15000
6     30000
7      6000
15    22500
21    12000
Name: 매출, dtype: int64
바닐라라떼

### TODO 7: 상위,하위 행과 `loc`

**요구사항**
- 매출 상위,하위 행을 뽑고, `loc`,`iloc` 으로 행,열을 집어냅니다.

**제한조건**
- 정답 확인용 `assert` 줄은 수정하지 않습니다. `None` 자리만 채웁니다.
- 조건부 대입은 사본 `df3` 에만 적용합니다. 원본 `df` 는 바꾸지 않습니다.

**힌트**
- 상위 5개 `df.nlargest(5, "매출")`, 하위 3개 `df.nsmallest(3, "수량")`.
- 행 조건 + 열 이름 `df.loc[df["지역"] == "부산", "매출"]`, 위치 기반 `df.iloc[0, 0]`.
- 조건부 대입 `df3.loc[df3["단가"] < 4500, "단가"] = 4500`.

In [23]:
# 1. 매출 상위 5개 주문을 상위5 에 할당해 주세요.
상위5 = df.nlargest(5, "매출")
assert len(상위5) == 5 and 상위5["매출"].iloc[0] == df["매출"].max(), "nlargest 결과가 올바르지 않습니다."

# 2. 수량 하위 3개 주문을 하위3 에 할당해 주세요.
하위3 = df.nsmallest(3, "수량")
assert len(하위3) == 3 and 하위3["수량"].max() <= df["수량"].min() + 1, "nsmallest 결과가 올바르지 않습니다."

# 3. 부산 지역의 매출 컬럼만 골라 부산매출 에 할당해 주세요.
부산매출 = df.loc[df["지역"] == "부산", "매출"]
assert isinstance(부산매출, pd.Series) and len(부산매출) == (df["지역"] == "부산").sum(), "loc 선택이 올바르지 않습니다."

# 4. 0행 0열의 값을 첫값 에 할당해 주세요. (위치 기반)
첫값 = df.iloc[0, 0]
assert 첫값 == df["지역"].iloc[0], "iloc 선택이 올바르지 않습니다."

# 5. 사본 df3 에서 단가가 4500 미만인 행의 단가를 4500 으로 올려 주세요. (조건부 대입)
df3 = df.copy()
df3.loc[df3["단가"] < 4500, "단가"] = 4500
assert df3["단가"].min() == 4500, "조건부 대입이 올바르지 않습니다."

print("TODO 7 통과!")

TODO 7 통과!

## Step 7: `groupby` 집계와 `pivot_table`

### Concept Check: groupby 로 그룹별 요약 만들기

`df.groupby("기준컬럼")["값컬럼"].집계함수()` 형태로 그룹별 요약을 만듭니다. 엑셀 피벗 테이블, SQL 의 `GROUP BY` 와 같은 발상입니다.

```python
df.groupby("지역")["매출"].sum()     # 지역별 총매출
df.groupby("메뉴")["단가"].mean()    # 메뉴별 평균 단가
df.groupby("지역")["메뉴"].count()   # 지역별 주문 건수
```

여러 집계를 동시에 낼 때는 `agg` 를 씁니다.

```python
df.groupby("지역").agg(
    매출합=("매출", "sum"),
    매출평균=("매출", "mean"),
    수량합=("수량", "sum"),
)
```

**다중 groupby 와 pivot_table**

- `groupby(["지역", "메뉴"])` - 두 개 이상 컬럼으로 묶으면 계층 인덱스(MultiIndex)가 생깁니다.
- `pivot_table(index=..., columns=..., values=..., aggfunc=...)` - `groupby` 와 결과는 비슷하나, 한 기준을 **가로(columns)로 펼칩니다.**
- 집계 결과는 인덱스가 그룹 키로 바뀌므로, `.reset_index()` 로 다시 일반 컬럼으로 되돌릴 수 있습니다.

**주의사항**

- 집계 컬럼을 `['매출']` 로 고르면 **Series**, `[['매출', '수량']]` 로 고르면 **DataFrame** 을 반환합니다.
- `count()` 는 결측(NaN)을 뺀 개수, `size()` 는 NaN 을 포함한 전체 행 수입니다.
- 집계 전 결측이 있으면 `mean` 이 왜곡되므로 먼저 처리합니다.
- `inplace=True` 는 원본을 직접 바꿔 되돌리기 어려우므로 사본에 재할당하는 방식을 권장합니다.

In [24]:
# Series 와 DataFrame 반환 차이, count 와 size 차이
print(type(df.groupby("지역")["매출"].sum()))          # Series
print(type(df.groupby("지역")[["매출", "수량"]].sum()))  # DataFrame

print(df.groupby("지역")["메뉴"].count())   # NaN 제외 개수
print(df.groupby("지역").size())            # NaN 포함 전체 행 수

<class 'pandas.Series'>
<class 'pandas.DataFrame'>
지역
광주    54
대전    54
부산    46
서울    46
Name: 메뉴, dtype: int64
지역
광주    54
대전    54
부산    46
서울    46
dtype: int64

### TODO 8: 그룹별로 묶어 집계하기

**요구사항**
- `groupby` 로 지역, 메뉴별 집계를 만들고 정렬합니다.

**제한조건**
- 정답 확인용 `assert` 줄은 수정하지 않습니다. `None` 자리만 채웁니다.

**힌트**
- 그룹 합계 `df.groupby("지역")["매출"].sum()`, 정렬 `Series.sort_values(ascending=False)`.
- 여러 집계 동시: `df.groupby("지역").agg(매출합=("매출", "sum"), 수량합=("수량", "sum"))`.

In [25]:
# 1. 지역별 총매출을 지역별매출 에 할당해 주세요.
지역별매출 = df.groupby("지역")["매출"].sum()
assert isinstance(지역별매출, pd.Series) and round(float(지역별매출.sum()), 2) == round(float(df["매출"].sum()), 2), "지역별 총매출이 올바르지 않습니다."

# 2. 메뉴별 평균 단가를 메뉴별평균단가 에 할당해 주세요.
메뉴별평균단가 = df.groupby("메뉴")["단가"].mean()
assert len(메뉴별평균단가) == 3, "메뉴별 평균 단가가 올바르지 않습니다."

# 3. 지역별 주문 건수를 지역별건수 에 할당해 주세요.
지역별건수 = df.groupby("지역").size()
assert 지역별건수.sum() == 200, "지역별 건수가 올바르지 않습니다."

# 4. 지역별매출 을 내림차순으로 정렬해 매출내림 에 할당해 주세요.
매출내림 = 지역별매출.sort_values(ascending=False)
assert list(매출내림.values) == sorted(지역별매출.values, reverse=True), "내림차순 정렬이 올바르지 않습니다."

# 5. 지역별 매출합, 매출평균, 수량합을 동시에 집계해 요약 에 할당해 주세요.
요약 = df.groupby("지역").agg(
    매출합=("매출", "sum"),
    매출평균=("매출", "mean"),
    수량합=("수량", "sum")
)
assert set(요약.columns) == {"매출합", "매출평균", "수량합"}, "agg 집계가 올바르지 않습니다."

print("TODO 8 통과!")
요약

TODO 8 통과!

       매출합          매출평균  수량합
지역
광주  879500  16287.037037  174
대전  742500  13750.000000  153
부산  760500  16532.608696  152
서울  748500  16271.739130  146

### TODO 9: 다중 `groupby` 와 `pivot_table`

**요구사항**
- 두 컬럼으로 묶어 집계하고, 같은 내용을 `pivot_table` 로 가로 펼침 형태로 만듭니다.

**제한조건**
- 정답 확인용 `assert` 줄은 수정하지 않습니다. `None` 자리만 채웁니다.

**힌트**
- 다중 그룹: `df.groupby(["지역", "메뉴"])["매출"].sum()` (MultiIndex).
- 가로 펼침: `df.pivot_table(index="지역", columns="메뉴", values="매출", aggfunc="sum")`.
- 인덱스를 일반 컬럼으로 되돌리기: `.reset_index()`.

In [26]:
# 1. 지역 × 메뉴별 총매출을 지역메뉴매출 에 할당해 주세요.
지역메뉴매출 = df.groupby(["지역", "메뉴"])["매출"].sum()
assert 지역메뉴매출.index.nlevels == 2 and len(지역메뉴매출) == 12, "다중 groupby 결과가 올바르지 않습니다."

# 2. 지역메뉴매출 의 인덱스를 일반 컬럼으로 되돌려 평평한표 에 할당해 주세요.
평평한표 = 지역메뉴매출.reset_index()
assert list(평평한표.columns) == ["지역", "메뉴", "매출"], "reset_index 결과가 올바르지 않습니다."

# 3. 지역(세로) × 메뉴(가로)로 매출 합계를 교차 집계해 피벗 에 할당해 주세요.
피벗 = df.pivot_table(
    index="지역",
    columns="메뉴",
    values="매출",
    aggfunc="sum"
)
assert 피벗.shape == (4, 3), "pivot_table 모양이 올바르지 않습니다."
assert round(float(피벗.sum().sum()), 2) == round(float(df["매출"].sum()), 2), "pivot_table 합계가 올바르지 않습니다."

print("TODO 9 통과!")
피벗

TODO 9 통과!

메뉴   바닐라라떼   아메리카노    카페라떼
지역
광주  202500  207000  470000
대전  235000  287500  220000
부산  313500  316000  131000
서울  309000  261500  178000

## Step 8: 미니 프로젝트 - 카페 매출 리포트

조회, 필터, 집계를 이용해 카페 매출 리포트를 완성합니다.

### TODO 10: 카페 매출 리포트

**요구사항**
1. `최고지역` - 총매출이 가장 큰 지역 이름
2. `메뉴별건수` - 메뉴별 주문 건수 (내림차순)
3. `서울아메평균` - 서울 지역 아메리카노의 평균 매출
4. `top3` - 매출 상위 3개 주문의 지역,메뉴,매출만 담은 표

**제한조건**
- 정답 확인용 `assert` 줄은 수정하지 않습니다. `None` 자리만 채웁니다.

**힌트**
- 가장 큰 값의 인덱스는 `Series.idxmax()`.
- 값별 빈도는 `value_counts()` 가 이미 내림차순입니다.
- 복합 조건 필터 뒤 `["매출"].mean()`.
- 상위 3행에서 열 고르기 `df.nlargest(3, "매출")[["지역", "메뉴", "매출"]]`.

In [27]:
# 1. 총매출이 가장 큰 지역 이름을 최고지역 에 담으세요.
최고지역 = df.groupby("지역")["매출"].sum().idxmax()
assert 최고지역 in ["서울", "부산", "대전", "광주"], "최고 매출 지역이 올바르지 않습니다."
assert df.groupby("지역")["매출"].sum()[최고지역] == df.groupby("지역")["매출"].sum().max(), "최고 매출 지역이 올바르지 않습니다."

# 2. 메뉴별 주문 건수를 메뉴별건수 에 담으세요. (내림차순)
메뉴별건수 = df["메뉴"].value_counts()
assert 메뉴별건수.sum() == 200 and list(메뉴별건수.values) == sorted(메뉴별건수.values, reverse=True), "메뉴별 건수가 올바르지 않습니다."

# 3. 서울 지역 아메리카노의 평균 매출을 서울아메평균 에 담으세요.
서울아메평균 = df[
    (df["지역"] == "서울") & (df["메뉴"] == "아메리카노")
]["매출"].mean()
assert 서울아메평균 > 0, "서울 아메리카노 평균 매출이 올바르지 않습니다."

# 4. 매출 상위 3개 주문의 지역,메뉴,매출만 담은 표를 top3 에 담으세요.
top3 = df.nlargest(3, "매출")[["지역", "메뉴", "매출"]]
assert list(top3.columns) == ["지역", "메뉴", "매출"] and len(top3) == 3, "top3 표가 올바르지 않습니다."

print("TODO 10 통과! 미니 프로젝트 완성")
print("최고 매출 지역:", 최고지역)
print("서울 아메리카노 평균 매출:", round(서울아메평균, 2))
top3

TODO 10 통과! 미니 프로젝트 완성
최고 매출 지역: 광주
서울 아메리카노 평균 매출: 13763.16

    지역     메뉴     매출
6   서울  바닐라라떼  30000
31  서울   카페라떼  30000
55  광주   카페라떼  30000

## 학생용 자가 체크리스트

- [ ] NumPy 배열로 벡터 연산,통계,조건 필터,정렬을 할 수 있다
- [ ] `reshape` 와 `axis` 축별 집계, 브로드캐스팅을 이해한다
- [ ] DataFrame 을 `head`/`tail`/`info`/`describe`/`value_counts` 로 조회할 수 있다
- [ ] `read_csv` / `to_csv` 로 파일을 읽고 쓸 수 있다
- [ ] 단일,복합 조건과 `isin`/`str.contains` 로 행을 필터링할 수 있다
- [ ] `nlargest`/`nsmallest` 와 `loc`/`iloc` 으로 원하는 행,열을 집어낼 수 있다
- [ ] `groupby` 와 `agg`, `pivot_table` 로 그룹별 집계를 만들 수 있다

---

### **Content License Agreement**

<font color='red'><b>**WARNING**</b></font> : 본 자료는 삼성청년SW,AI아카데미의 콘텐츠 자산으로, 보안서약서에 의거하여 어떠한 사유로도 임의로 복사, 촬영, 녹음, 복제, 보관, 전송하거나 허가 받지 않은 저장매체를 이용한 보관, 제3자에게 누설, 공개 또는 사용하는 등의 무단 사용 및 불법 배포 시 법적 조치를 받을 수 있습니다.